### ISSUE TITLE
Bug: Fails to compress JSON-like text

### ISSUE THREAD

**Issue by grimen** [dudleycarr/snappystream#38] opened 2019-07-15 03:35 UTC
**Code:**

```javascript

const fs = require('fs')
const JSONStream = require('JSONStream')
const { SnappyStream } = require('snappystream')

const snappyStream = new SnappyStream()
const outStream = fs.createWriteStream('./compressed.sz')

// const inStream = fs.createReadStream('./works.txt')
const inStream = fs.createReadStream('./fails.txt')

inStream
    .pipe(snappyStream)
    .pipe(JSONStream.stringify())
    .pipe(process.stdout)
    .pipe(outStream)

```

**Input:** `fails.txt`

```
{
    "foo": "bar"
}
```

**Output:**

```shell
➜  snappstream-test node compress.js
[
{"type":"Buffer","data":[255,6,0,0,115,78,97,80,112,89]}internal/buffer.js:58
    throw new ERR_OUT_OF_RANGE('value', range, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 4_428_318_634
    at checkInt (internal/buffer.js:58:11)
    at writeU_Int32LE (internal/buffer.js:678:3)
    at Buffer.writeUInt32LE (internal/buffer.js:691:10)
    at /home/jonas/Desktop/snappstream-test/node_modules/snappystream/lib/snappystreams.js:83:22
    at /home/jonas/Desktop/snappstream-test/node_modules/snappystream/node_modules/async/dist/async.js:1140:9
    at /home/jonas/Desktop/snappstream-test/node_modules/snappystream/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/jonas/Desktop/snappstream-test/node_modules/snappystream/node_modules/async/dist/async.js:1064:13)
    at /home/jonas/Desktop/snappstream-test/node_modules/snappystream/node_modules/async/dist/async.js:969:16
    at /home/jonas/Desktop/snappstream-test/node_modules/snappystream/node_modules/async/dist/async.js:1137:13
```

**Input:** `works.txt`

```
{
    "foo": "bar"
}
```

```shell
➜  snappstream-test node compress.js
[
{"type":"Buffer","data":[255,6,0,0,115,78,97,80,112,89]}
,
{"type":"Buffer","data":[1,23,0,0,237,49,157,176,123,10,32,32,32,32,34,102,111,111,34,58,32,98,97,114,10,125,10]}
]
```

**Comment by dudleycarr** [comment] 2021-07-08 14:26
Sorry about the 2 year turn around on this issue. I'm not able to reproduce the error you have with the code above. The input files also look identical. Closing, but if for some reason this is still an issue, please re-open.

**Closed by dudleycarr** 2021-07-08 14:26 UTC
