### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by ofkindness** [dudleycarr/snappystream#4] opened 2015-10-26 23:26 UTC
I have found this bug only on linux. This build buildpack-deps:jessie https://github.com/nodejs/docker-node/blob/master/4.2/Dockerfile 
NODE_VERSION 4.2.1

Error: Could not locate the bindings file. Tried:
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build/Debug/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build/Release/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/out/Debug/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/Debug/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/out/Release/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/Release/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build/default/binding.node
 → /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/compiled/4.2.1/linux/x64/binding.node
    at bindings (/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/snappy.js:2:34)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node_modules/nsqjs/node_modules/snappystream/lib/snappystreams.js:9:10)

**Comment by nololabout** [comment] 2015-11-17 16:36
node-gyp rebuild

from /node_modules/nsqjs/node_modules/snappystream/node_modules/snappy actually helps, but its quite annoying to do so every time

**Comment by mtlima** [comment] 2015-12-04 15:02
I actually don't get this error when using npm@2.12.1 and node 0.10.40
With npm@2.14.* and 3.5.2 this happens on both 0.10.40 and 4.2.2.

Doing node-gyp rebuild from that path solves the problem, but it's quite an ugly thing to have on a Dockerfile

**Comment by mindnuts** [comment] 2016-01-19 14:01
can confirm the same thing happening on Node.js v4.2.4 and NPM 2.14.12. Fix is to rebuild as mentioned by @pieceofkindness.

BTW, we are using node-gyp and not pangyp.

**Comment by hilkeheremans** [comment] 2016-02-12 12:48
Same here on Linux (both Ubuntu on bare metal and Alpine inside Docker).

**Comment by kenjones-cisco** [comment] 2016-06-24 22:31
Not sure if this will help everyone but after hitting this issue and applying the `node-gyp rebuild` as my `postinstall` script for my project. I start looking for the root cause of `npm WARN cannot run in wd snappy@4.1.1 node-gyp rebuild`. 

That is when I ran across http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd and realized that the real root cause was install as user `root`. My preferred install is inside a container and even though I had created another user account and made it the owner of the `/app` directory I was installing into, the warning was being displayed. So I executed npm install via my non-root user and the warning went away as well as the runtime error of not being able to locate the binding file.

Hopefully this can help others as well.

**Comment by dudleycarr** [comment] 2017-01-02 22:44
Closing this since this seems to be Node 4.2.1 specific issue.

**Closed by dudleycarr** 2017-01-02 22:44 UTC

**Comment by FewKinG** [comment] 2017-01-11 12:25
I have this issue using node 7.4.0, npm 4.0.5.
First I had to install g++/gcc version 5 to be able to install and compile, then I ran in to the issue mentioned above:

> nsq = require('nsqjs')
Error: Could not locate the bindings file. Tried:
 → /home/sessionline/ti/backend/node_modules/snappy/build/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/build/Debug/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/build/Release/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/out/Debug/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/Debug/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/out/Release/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/Release/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/build/default/binding.node
 → /home/sessionline/ti/backend/node_modules/snappy/compiled/7.4.0/linux/ia32/binding.node
    at bindings (/home/sessionline/ti/backend/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/sessionline/ti/backend/node_modules/snappy/snappy.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sessionline/ti/backend/node_modules/snappystream/lib/snappystreams.js:9:10)

**Comment by ghafran** [comment] 2017-04-11 17:44
npm rebuild 
seems to fix this. I am running nodejs v6.10.2 with nsqjs v0.8.4.

**Comment by lizwangying** [comment] 2018-03-23 03:47
thanks ,  `npm rebuild`  works , nodejs v9.8.0

**Comment by rihannarickeminem** [comment] 2018-06-23 05:58
i use node 10 and also got this error

**Comment by vipulDessai** [comment] 2022-08-01 06:22
Thanks for pointing out the error comes due to `node rebuild`, but I was creating an AWS lambda layer on mac, and since its put on the amazon Linux instance, I was getting this same error, so I took the amazonlinux docker image and created a layer on it and attached it to my lambda and it works now 😎
